#!/usr/bin/python3
import sys

def factorize(number):
    for p in range(2, number + 1):
        if number % p == 0:
            q = number // p
            return f"{number}={p}*{q}"


if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

input_file = sys.argv[1]

try: 
    with open(input_file, "r") as file:
        for line in file:
            number = int(line.strip())
            factorization = factorize(number)
            if factorization:
                print(factorization)
except FileNotFoundError:
    print(f"File '{input_file}' not found.")
    sys.exit(1)
except ValueError:
    print("Invalid number in the file.")
    sys.exit(1)
    
